#!/usr/bin/env python
import json
import requests

import bs4
from bs4 import BeautifulSoup

BASE_URL = "https://news.google.com"
QUERY_STRINGS = "?hl=pt-BR&gl=BR&ceid=BR:pt-419"

def main():
    news = requests.get(f"{BASE_URL}/topstories{QUERY_STRINGS}")
    soup = BeautifulSoup(news.text, "html.parser")

    news_list = []

    for article in soup.select("article"):
        title = article.select("h3 a")
        
        title = article.select("h4 a")[0].text if not title else title[0].get("href")
        url = article.select("h4 a")[0].get("href") if not title else title[0].text
        
        news_list.append({
            "title": title, 
            "url": f"{BASE_URL}/{url}{QUERY_STRINGS}"
        })

    print(json.dumps(news_list))

if __name__ == "__main__":
    main()
